### ISSUE TITLE
Need help regarding Broker Installation

### ISSUE THREAD

**Issue by sami2316** [bro/broker#1]
I tried to install broker on centos, fedora and security-onion but get the same error:

"""""CMake Error at CMakeLists.txt:3 (include):
  include could not find load file:

    cmake/CommonCMakeConfig.cmake

CMake Error at CMakeLists.txt:5 (find_package):
  By not providing "FindLibcaf.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Libcaf", but
  CMake did not find one.

  Could not find a package configuration file provided by "Libcaf" with any
  of the following names:

    LibcafConfig.cmake
    libcaf-config.cmake

  Add the installation prefix of "Libcaf" to CMAKE_PREFIX_PATH or set
  "Libcaf_DIR" to a directory containing one of the above files.  If "Libcaf"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!"""""

Please guide me. Thanks ahead.

**Comment by jsiwek** [comment]
Looks like a git submodule needs to be initialized.  In an already-existing clone, the `git submodule update --recursive --init` command should take care of that.

Or if you're starting from a fresh clone, using `git clone --recursive` would clone the broker repo as well as any git submodules it depends on.

**Comment by sami2316** [comment]
Thanks for you reply. I tried that command but getting the following error.

"""Cloning into 'broker'...
remote: Counting objects: 1364, done.
remote: Compressing objects: 100% (44/44), done.
Receiving objects: 100% (1364/1364), 2.19 MiB | 532 KiB/s, done.
remote: Total 1364 (delta 12), reused 0 (delta 0), pack-reused 1319
Resolving deltas: 100% (1012/1012), done.
Submodule 'cmake' (git://git.bro.org/cmake) registered for path 'cmake'
Cloning into 'cmake'...
fatal: unable to connect to git.bro.org:
git.bro.org: Temporary failure in name resolution

Clone of 'git://git.bro.org/cmake' into submodule path 'cmake' failed
""""

**Comment by jsiwek** [comment]
That's odd, maybe looks like a transient network/DNS issue.  Can you actually resolve `git.bro.org` (e.g. what does `host git.bro.org` tell you) or have you just tried again at a later time?

**Comment by sami2316** [comment]
cloning into 'cmake' resolved. Now it is working. But when i try "./configure", I get the following error
""""./configure 
Build Directory : build
Source Directory: /home/user/broker
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find Libcaf (missing: LIBCAF_LIBRARIES LIBCAF_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibcaf.cmake:90 (find_package_handle_standard_args)
  CMakeLists.txt:5 (find_package)
""""

**Comment by sami2316** [comment]
I resolved the above error, but now getting error in "make" command

""""""""""""[  9%] Building CXX object CMakeFiles/broker.dir/src/endpoint.cc.o
In file included from /home/user/broker/src/endpoint.cc:2:0:
/home/user/broker/src/endpoint_impl.hh: In lambda function:
/home/user/broker/src/endpoint_impl.hh:212:47: error: ‘current_sender’ was not declared in this scope
    bool from_peer = peers.find(current_sender()) != peers.end();
                                               ^
/home/user/broker/src/endpoint_impl.hh: In lambda function:
/home/user/broker/src/endpoint_impl.hh:337:50: error: ‘current_message’ was not declared in this scope
                 + caf::to_string(current_message()));
                                                  ^
/home/user/broker/src/endpoint_impl.hh: In member function ‘void broker::endpoint_actor::publish_current_msg_to_peers(const topic&, int)’:
/home/user/broker/src/endpoint_impl.hh:453:51: error: ‘current_message’ was not declared in this scope
                 send(p.second.ep, current_message());
                                                   ^
/home/user/broker/src/endpoint_impl.hh:456:41: error: ‘current_message’ was not declared in this scope
                 send(a, current_message());
                                         ^
/home/user/broker/src/endpoint_impl.hh: In lambda function:
/home/user/broker/src/endpoint_impl.hh:557:50: error: ‘current_message’ was not declared in this scope
                 + caf::to_string(current_message()));
                                                  ^
CMakeFiles/broker.dir/build.make:123: recipe for target 'CMakeFiles/broker.dir/src/endpoint.cc.o' failed
make[3]: *** [CMakeFiles/broker.dir/src/endpoint.cc.o] Error 1
make[3]: Leaving directory '/home/user/broker/build'
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/broker.dir/all' failed
make[2]: *** [CMakeFiles/broker.dir/all] Error 2
make[2]: Leaving directory '/home/user/broker/build'
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/user/broker/build'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2
"""""""""""""""""

**Comment by jsiwek** [comment]
Broker currently depends on the `develop` branch of libcaf.  So, if you have a clone of actor-framework do `git checkout develop` in it and then rebuild/reinstall.

**Comment by sami2316** [comment]
"git checkout develop" 
worked for me. Thanks a lot.

**Comment by sami2316** [comment]
Can you please look at this error. Error came in the make command

/usr/bin/ld: /usr/local/lib/librocksdb.a(db_impl.o): relocation R_X86_64_32S against `_ZTVN7rocksdb2DBE' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/librocksdb.a: could not read symbols: Bad value

**Comment by jsiwek** [comment]
The compile error is hinting that if you intend to link the static library, librocksdb.a, into a shared library, libbroker.so here, then librocksdb.a should have been compiled with the -fPIC flag, but it wasn't.

So if you compiled librocksdb.a yourself, try again but with -fPIC.

Alternatively, since I think most build systems would set things up to implicitly add PIC support when compiling things into a shared library, you could try using a shared version, librocksdb.so, and link against that (you may have to start from a fresh broker ./configure for it to find the new .so).

**Comment by sami2316** [comment]
how can i pass librocksdb.so path to ./configure of broker? Because default behaviour is librocksdb.a.

**Comment by jsiwek** [comment]
Did you remove build/CMakeCache.txt before doing ./configure again?

If it still picks up the static version first, I guess there's not currently a way to get it to prefer the shared library without making some changes to either the CMake or configure scripts.  But if you don't need librocksdb.a for anything else, you could consider just deleting/uninstalling it as a workaround.

**Comment by sami2316** [comment]
I used 
   ./configure --with-rocksdb=/usr/local/lib/librocksdb.so
and it worked. Thanks for your reply.

**Comment by sami2316** [comment]
Please look at this error. What could be the possible reason..? 


In file included from /home/bproject/broker/src/queue_impl.hh:6:0,
                 from /home/bproject/broker/src/queue.cc:1:
/home/bproject/broker/src/util/queue_actor.hh: In instantiation of ‘broker::util::queue_actor<Pattern, Message>::queue_actor(broker::util::flare) [with Pattern = caf::detail::advanced_match_case_builder<caf::detail::type_list<caf::unit_t>, caf::detail::type_list<std::vector<broker::data, std::allocator<broker::data> > > >; Message = std::vector<broker::data>]’:
/home/bproject/actor-framework/libcaf_core/caf/detail/embedded.hpp:35:36:   required from ‘caf::detail::embedded<Base>::embedded(caf::intrusive_ptr<caf::ref_counted>, Ts&& ...) [with Ts = {broker::util::flare}; Base = broker::util::queue_actor<caf::detail::advanced_match_case_builder<caf::detail::type_list<caf::unit_t>, caf::detail::type_list<std::vector<broker::data, std::allocator<broker::data> > > >, std::vector<broker::data> >]’
/home/bproject/actor-framework/libcaf_core/caf/detail/memory.hpp:204:5:   required from ‘static T* caf::detail::memory::create(Ts&& ...) [with T = broker::util::queue_actor<caf::detail::advanced_match_case_builder<caf::detail::type_list<caf::unit_t>, caf::detail::type_list<std::vector<broker::data, std::allocator<broker::data> > > >, std::vector<broker::data> >; Ts = {broker::util::flare}]’
/home/bproject/actor-framework/libcaf_core/caf/make_counted.hpp:40:76:   required from ‘typename std::enable_if<caf::detail::is_memory_cached<T>::value, caf::intrusive_ptr<T> >::type caf::make_counted(Ts&& ...) [with T = broker::util::queue_actor<caf::detail::advanced_match_case_builder<caf::detail::type_list<caf::unit_t>, caf::detail::type_list<std::vector<broker::data, std::allocator<broker::data> > > >, std::vector<broker::data> >; Ts = {broker::util::flare}; typename std::enable_if<caf::detail::is_memory_cached<T>::value, caf::intrusive_ptr<T> >::type = caf::intrusive_ptr<broker::util::queue_actor<caf::detail::advanced_match_case_builder<caf::detail::type_list<caf::unit_t>, caf::detail::type_list<std::vector<broker::data, std::allocator<broker::data> > > >, std::vector<broker::data> > >]’
/home/bproject/actor-framework/libcaf_core/caf/spawn.hpp:57:53:   required from ‘caf::intrusive_ptr<T> caf::spawn_impl(caf::execution_unit*, BeforeLaunch, Ts&& ...) [with C = broker::util::queue_actor<caf::detail::advanced_match_case_builder<caf::detail::type_list<caf::unit_t>, caf::detail::type_list<std::vector<broker::data, std::allocator<broker::data> > > >, std::vector<broker::data> >; caf::spawn_options Os = (caf::spawn_options)32; BeforeLaunch = caf::empty_before_launch_callback; Ts = {broker::util::flare}]’
/home/bproject/actor-framework/libcaf_core/caf/spawn.hpp:78:56:   required from ‘caf::intrusive_ptr<T> caf::spawn_class(caf::execution_unit*, BeforeLaunch, Ts&& ...) [with C = broker::util::queue_actor<caf::detail::advanced_match_case_builder<caf::detail::type_list<caf::unit_t>, caf::detail::type_list<std::vector<broker::data, std::allocator<broker::data> > > >, std::vector<broker::data> >; caf::spawn_options Os = (caf::spawn_options)32; BeforeLaunch = caf::empty_before_launch_callback; Ts = {broker::util::flare}]’
/home/bproject/actor-framework/libcaf_core/caf/spawn.hpp:125:52:   required from ‘caf::actor caf::spawn(Ts&& ...) [with C = broker::util::queue_actor<caf::detail::advanced_match_case_builder<caf::detail::type_list<caf::unit_t>, caf::detail::type_list<std::vector<broker::data, std::allocator<broker::data> > > >, std::vector<broker::data> >; caf::spawn_options Os = (caf::spawn_options)32; Ts = {broker::util::flare}]’
/home/bproject/broker/src/queue_impl.hh:22:44:   required from ‘broker::queue<T>::impl::impl() [with T = std::vector<broker::data>]’
/home/bproject/broker/src/queue.cc:39:24:   required from here
/home/bproject/broker/src/util/queue_actor.hh:32:14: error: no matching function for call to ‘caf::detail::advanced_match_case_builder<caf::detail::type_list<caf::unit_t>, caf::detail::type_list<std::vector<broker::data, std::allocator<broker::data> > > >::advanced_match_case_builder()’
    Pattern() >> [=](Message& msg)
              ^
/home/bproject/broker/src/util/queue_actor.hh:32:14: note: candidates are:
In file included from /home/bproject/actor-framework/libcaf_core/caf/on.hpp:42:0,
                 from /home/bproject/actor-framework/libcaf_core/caf/event_based_actor.hpp:25,
                 from /home/bproject/actor-framework/libcaf_core/caf/sb_actor.hpp:26,
                 from /home/bproject/broker/src/util/queue_actor.hh:6,
                 from /home/bproject/broker/src/queue_impl.hh:6,
                 from /home/bproject/broker/src/queue.cc:1:
/home/bproject/actor-framework/libcaf_core/caf/detail/match_case_builder.hpp:240:3: note: template<class ... Fs> caf::detail::advanced_match_case_builder<Projections, Pattern>::advanced_match_case_builder(caf::detail::variadic_ctor, Fs ...)
   advanced_match_case_builder(variadic_ctor, Fs... fs)
   ^
/home/bproject/actor-framework/libcaf_core/caf/detail/match_case_builder.hpp:240:3: note:   template argument deduction/substitution failed:
In file included from /home/bproject/broker/src/queue_impl.hh:6:0,
                 from /home/bproject/broker/src/queue.cc:1:
/home/bproject/broker/src/util/queue_actor.hh:32:14: note:   candidate expects 2 arguments, 0 provided
    Pattern() >> [=](Message& msg)
              ^
In file included from /home/bproject/actor-framework/libcaf_core/caf/on.hpp:42:0,
                 from /home/bproject/actor-framework/libcaf_core/caf/event_based_actor.hpp:25,
                 from /home/bproject/actor-framework/libcaf_core/caf/sb_actor.hpp:26,
                 from /home/bproject/broker/src/util/queue_actor.hh:6,
                 from /home/bproject/broker/src/queue_impl.hh:6,
                 from /home/bproject/broker/src/queue.cc:1:
/home/bproject/actor-framework/libcaf_core/caf/detail/match_case_builder.hpp:214:7: note: constexpr caf::detail::advanced_match_case_builder<caf::detail::type_list<caf::unit_t>, caf::detail::type_list<std::vector<broker::data, std::allocator<broker::data> > > >::advanced_match_case_builder(const caf::detail::advanced_match_case_builder<caf::detail::type_list<caf::unit_t>, caf::detail::type_list<std::vector<broker::data, std::allocator<broker::data> > > >&)
 class advanced_match_case_builder : public message_case_builder {
       ^
/home/bproject/actor-framework/libcaf_core/caf/detail/match_case_builder.hpp:214:7: note:   candidate expects 1 argument, 0 provided
/home/bproject/actor-framework/libcaf_core/caf/detail/match_case_builder.hpp:214:7: note: constexpr caf::detail::advanced_match_case_builder<caf::detail::type_list<caf::unit_t>, caf::detail::type_list<std::vector<broker::data, std::allocator<broker::data> > > >::advanced_match_case_builder(caf::detail::advanced_match_case_builder<caf::detail::type_list<caf::unit_t>, caf::detail::type_list<std::vector<broker::data, std::allocator<broker::data> > > >&&)
/home/bproject/actor-framework/libcaf_core/caf/detail/match_case_builder.hpp:214:7: note:   candidate expects 1 argument, 0 provided
In file included from /home/bproject/broker/src/queue_impl.hh:6:0,
                 from /home/bproject/broker/src/queue.cc:1:
/home/bproject/broker/src/util/queue_actor.hh:38:4: error: no matching function for call to ‘caf::message_handler::message_handler(<brace-enclosed initializer list>)’
    };
    ^
/home/bproject/broker/src/util/queue_actor.hh:38:4: note: candidates are:
In file included from /home/bproject/actor-framework/libcaf_core/caf/continue_helper.hpp:28:0,
                 from /home/bproject/actor-framework/libcaf_core/caf/typed_continue_helper.hpp:23,
                 from /home/bproject/actor-framework/libcaf_core/caf/typed_behavior.hpp:26,
                 from /home/bproject/actor-framework/libcaf_core/caf/typed_actor.hpp:29,
                 from /home/bproject/actor-framework/libcaf_core/caf/spawn_fwd.hpp:27,
                 from /home/bproject/actor-framework/libcaf_core/caf/local_actor.hpp:37,
                 from /home/bproject/actor-framework/libcaf_core/caf/event_based_actor.hpp:27,
                 from /home/bproject/actor-framework/libcaf_core/caf/sb_actor.hpp:26,
                 from /home/bproject/broker/src/util/queue_actor.hh:6,
                 from /home/bproject/broker/src/queue_impl.hh:6,
                 from /home/bproject/broker/src/queue.cc:1:
/home/bproject/actor-framework/libcaf_core/caf/message_handler.hpp:75:3: note: template<class T, class ... Ts> caf::message_handler::message_handler(const T&, Ts&& ...)
   message_handler(const T& v, Ts&&... xs) {
   ^
/home/bproject/actor-framework/libcaf_core/caf/message_handler.hpp:75:3: note:   template argument deduction/substitution failed:
/home/bproject/actor-framework/libcaf_core/caf/message_handler.hpp:65:3: note: caf::message_handler::message_handler(caf::message_handler::impl_ptr)
   message_handler(impl_ptr ptr);
   ^
/home/bproject/actor-framework/libcaf_core/caf/message_handler.hpp:65:3: note:   candidate expects 1 argument, 2 provided
/home/bproject/actor-framework/libcaf_core/caf/message_handler.hpp:52:3: note: caf::message_handler::message_handler(const caf::message_handler&)
   message_handler(const message_handler&) = default;
   ^
/home/bproject/actor-framework/libcaf_core/caf/message_handler.hpp:52:3: note:   candidate expects 1 argument, 2 provided
/home/bproject/actor-framework/libcaf_core/caf/message_handler.hpp:51:3: note: caf::message_handler::message_handler(caf::message_handler&&)
   message_handler(message_handler&&) = default;
   ^
/home/bproject/actor-framework/libcaf_core/caf/message_handler.hpp:51:3: note:   candidate expects 1 argument, 2 provided
/home/bproject/actor-framework/libcaf_core/caf/message_handler.hpp:50:3: note: constexpr caf::message_handler::message_handler()
   message_handler() = default;
   ^
/home/bproject/actor-framework/libcaf_core/caf/message_handler.hpp:50:3: note:   candidate expects 0 arguments, 2 provided
/home/bproject/broker/src/util/queue_actor.hh:42: confused by earlier errors, bailing out
Preprocessed source stored into /tmp/ccKIKMC8.out file, please attach this to your bugreport.
make[3]: *** [CMakeFiles/broker.dir/src/queue.cc.o] Error 1
make[3]: Leaving directory `/home/bproject/broker/build'
make[2]: *** [CMakeFiles/broker.dir/all] Error 2
make[2]: Leaving directory `/home/bproject/broker/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/bproject/broker/build'
make: *** [all] Error 2

**Comment by jsiwek** [comment]
What version of CAF?  What compiler & compiler version?  What OS?

Did you have a working build before?  What's different/changed?

**Comment by sami2316** [comment]
The C compiler identification is GNU 4.8.3
-- The CXX compiler identification is GNU 4.8.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Libcaf: /home/bproject/actor-framework/build/lib/libcaf_core.so;/home/bproject/actor-framework/build/lib/libcaf_io.so  
-- Found CAF version: 0.13.2


Yes I had a working build at Centos 7. But now I'm trying to install it in another Centos  7 and getting the above error.... Following the same steps.

**Comment by sami2316** [comment]
@jsiwek any idea about error?

**Comment by jsiwek** [comment]
I'm not sure: compilation of Broker's master branch still works fine for me on CentOS 7, with GCC 4.8.3 and CAF 0.13.2.  Maybe can you start from scratch and record an explicit list of steps/commands that could be used to reproduce the error?

**Comment by sami2316** [comment]
It did't worked for me with CAF 0.13.2. I tried many times from scratch but finally
It works with CAF 0.13.0 and  rocksdb 3.10.

**Comment by sami2316** [comment]
I tried broker; it works at local pc with 
pc1.listen(9999,"192.168.1.90") and peer function. But when I try to put these functions on two different computer, connection does not establish. 
ERROR : new_tcp_connection_impl couuld not connect to 192.168.1.90 at 9999. 
What could be the possible reason?

**Comment by mavam** [comment]
@sami2316 could you share the error message (or symptoms) you get when using CAF 0.13.2?

**Comment by mavam** [comment]
@jsiwek I could imagine that this occurs because `queue.hh` only includes these two CAF headers:

```cpp
#include <caf/spawn.hpp>
#include <caf/send.hpp>
```

@sami2316 Could you do us a favor and try adding `#include <caf/all.hpp>` in `src/queue.cc` at the top just to see if that fixes the issue?

**Comment by sami2316** [comment]
@mavam 
#include "caf/spawn.hpp"
#include "caf/send.hpp"
these headers are in queque_impl.hh file. 
I tried adding  #include <caf/all.hpp> but it did't work. It just works on the same computer.

**Comment by sami2316** [comment]
@jsiwek please take a look at library why remote connection is not working?

**Comment by jsiwek** [comment]
I'd check if the connecting host can even do something like `nc -zv 192.168.1.90 9999` after the listener has been started (you could even use a netcat listener instead of broker).  If that fails you've got some basic network connectivity issue; maybe first check firewall settings.

**Comment by sami2316** [comment]
@jsiwek When I allowed 9999/tcp in firewall, I am getting following error at listener side:
```
[ERROR] NONE::range_check: range_check failed
RUN finished Segmentation fault: core dumped
```
where I'm wrong?

**Comment by jsiwek** [comment]
Do you have example code to reproduce it (both listener and connector side) ?  Or can you run inside a debugger and capture a stack trace?

Just grepping quickly for "range_check", it seems that's within CAF's deserialization code, so the only other thought I have is maybe a connection sent "garbage" ?  Do you know if the error occurred in response to your own connection, or is the listener now open to the Internet?

**Comment by sami2316** [comment]
listener side code:
```C++
broker::init();
    broker::endpoint pc2("Printer");
    pc2.listen(9999,"192.168.1.187");
   // broker::endpoint pc1("Test");
   // pc1.peer("192.168.1.187",9999);
    
    std::cout<<"Listing"<<std::endl;
    auto conn_status = pc2.incoming_connection_status().need_pop();
    std::cout<<"Out of Pop function"<<std::endl;
    for (auto cs : conn_status)
    {
        if(cs.status == broker::incoming_connection_status::tag::established)
        {
            std::cout<< "Connection Established";
        }
        else
        {
            std::cout<<"Connection could not Establish";
        }
    }
```
At connector side: I'm just peering. 
When I tried debuging, It says:
```
Signal received: SIGSEGV (segmentation Error)
``` 
and then there is following information:
```
caf::detail::message_data::equals(caf::detail::message_data const&) const+0: push   %r15
caf::detail::message_data::equals(caf::detail::message_data const&) const+2: push   %r14
caf::detail::message_data::equals(caf::detail::message_data const&) const+4: push   %r13
caf::detail::message_data::equals(caf::detail::message_data const&) const+6: push   %r12
caf::detail::message_data::equals(caf::detail::message_data const&) const+8: push   %rbp
caf::detail::message_data::equals(caf::detail::message_data const&) const+9: mov    %rsi,%rbp
caf::detail::message_data::equals(caf::detail::message_data const&) const+12: push   %rbx
caf::detail::message_data::equals(caf::detail::message_data const&) const+13: mov    %rdi,%rbx
caf::detail::message_data::equals(caf::detail::message_data const&) const+16: sub    $0x68,%rsp
caf::detail::message_data::equals(caf::detail::message_data const&) const+20: cmp    %rsi,%rdi
caf::detail::message_data::equals(caf::detail::message_data const&) const+23: je     0x7ffff679f3b8 <caf::detail::message_data::equals(caf::detail::message_data const&) const+488>
caf::detail::message_data::equals(caf::detail::message_data const&) const+29: mov    (%rdi),%rax
caf::detail::message_data::equals(caf::detail::message_data const&) const+32: callq  *0x20(%rax)
caf::detail::message_data::equals(caf::detail::message_data const&) const+35: mov    %rax,%r13
caf::detail::message_data::cow_ptr::get_detached()+16: cmp    $0x1,%rax
caf::detail::message_data::cow_ptr::get_detached()+20: je     0x7ffff679f1bc <caf::detail::message_data::cow_ptr::get_detached()+60>
caf::detail::message_data::cow_ptr::get_detached()+22: mov    (%rbx),%rax
caf::detail::message_data::cow_ptr::get_detached()+25: mov    %rsp,%rdi
caf::detail::message_data::cow_ptr::get_detached()+28: mov    %rbx,%rsi
caf::detail::message_data::cow_ptr::get_detached()+31: callq  *0x50(%rax)
caf::detail::message_data::cow_ptr::get_detached()+60: add    $0x18,%rsp
caf::detail::message_data::cow_ptr::get_detached()+64: mov    %rbx,%rax
caf::detail::message_data::cow_ptr::get_detached()+67: pop    %rbx
caf::detail::message_data::cow_ptr::get_detached()+68: pop    %rbp
caf::detail::message_data::cow_ptr::get_detached()+69: retq   
0x00007ffff679f1c6: nopw   %cs:0x0(%rax,%rax,1)
```

**Comment by jsiwek** [comment]
You listener-side code worked for me across hosts, but I may be doing something on the connector-side.  Please post the code you're using.

And you using the same version of CAF on both hosts now?

**Comment by sami2316** [comment]
Connector side code:
```C++
broker::init();
broker::endpoint pc1("VM");
pc1.peer("192.168.1.187",9999);
std::cout<<"Peer Thrown"<<std::endl;
```
At listener-side I'm using CAF version 0.13.0, at connector side I'm not sure but hopefully I would be 0.13.x, I'll confirm tomorrow.

**Comment by sami2316** [comment]
@jsiwek 
*At both sides (connector and listener):* I have
```CAF version 0.3.10
broker version 0.4-1.0```
But still there is segmentation fault (SIGSEGV signal at debug time).

**Comment by jsiwek** [comment]
I notice there's a mention of `abstract_broker` in that stack trace and I think that's not in any released version of CAF, just its `develop` branch.  So probably at least the version of CAF you are using is not the one you think you are using and it may be the two sides have mismatched CAF versions.

How are obtaining CAF?  From git?  I'd suggest going back and cleaning out the CAF install on both systems and then making sure you actually get a 0.13.x release of it.

**Comment by sami2316** [comment]
I'm obtaining CAF from github. Firstly, I compiled it with ```git checkout develop``` but with this _broker_ code does not compile, it comes up with message_handler() arguments mismatch error. Then I tried ```git checkout 0.13.1``` at CAF. Every thing compiles fine but when I test broker example, it comes up with same ```range_check ``` error.
I tried different versions of broker as well as CAF (but same at both sides); It comes up with same error.

**Comment by sami2316** [comment]
@jsiwek I'm using Centos7. Can you please share your side versions of CAF and broker?

**Comment by jsiwek** [comment]
I was testing CentOS 7, CAF 0.13.2 and broker's `master` branch.

Broker isn't updated for API changes in CAF's `develop` branch, just official releases, so that's why that doesn't work at the moment.

But what I was getting at is that even though you say you have things compiled to use CAF 0.13.1, the stack trace you posted I see goes through `caf::io::abstract_broker` at one point and that seems to be something that's only in CAF's `develop` branch, not an official release.

So my guesses at the moment are that you've either 1) compiled/installed stuff in an inconsistent way or 2) not reported consistent information to me.

**Comment by sami2316** [comment]
It is working with CAF's version 0.13.2 (released version not from *github*) and broker's ```master``` branch. 
I was trying from github that did't work for remote connections (neither with ```develop``` branch or others). 

Thank you for you guidance :)

**Comment by fhightower** [comment]
<<<
cloning into 'cmake' resolved. Now it is working. But when i try "./configure", I get the following error
""""./configure 
Build Directory : build
Source Directory: /home/user/broker
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
Could NOT find Libcaf (missing: LIBCAF_LIBRARIES LIBCAF_INCLUDE_DIRS)
Call Stack (most recent call first):
/usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
cmake/FindLibcaf.cmake:90 (find_package_handle_standard_args)
CMakeLists.txt:5 (find_package)
""""
>>>

Hi sami2316, do you remember how you solved the problem that you mentioned above with the "Could NOT find Libcaf (missing: LIBCAF_LIBRARIES LIBCAF_INCLUDE_DIRS)" error?

**Comment by mavam** [comment]
@fhightower If you experience the same issue, please tell us a little more about your setup by posting the build summary and how you invoked configure. 

The error indicates that CMake cannot find CAF. If you've installed CAF manually, try passing `--with-libcaf=/path/to/caf/build`.

**Comment by fhightower** [comment]
Thanks for the reply!

Actually, I got it figured out.  If you have homebrew, you can install bro using homebrew:
http://brewformulas.org/Bro

Thanks though!

**Comment by HungryHumps** [comment]
I've also ran into the same problem after following this link: http://ossectools.blogspot.hk/2011/09/bro-quickstart-cluster-edition.html , namely:
`CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):`
`  Could NOT find Libcaf (missing: LIBCAF_LIBRARIES LIBCAF_INCLUDE_DIRS)`
I am also running CentOS 7.
(I want to resolve this problem rather than find a fix)
(during installation, I encountered : 
`/usr/bin/ld: cannot find -lnuma`
`collect2: error: ld returned 1 exit status`
`make: *** [tcpdump] Error 1`
while running
`./configure --prefix=/usr/local/pfring && make && sudo make install`
during PC_RING installation
)

**Comment by fhightower** [comment]
@HungryHumps: I was recently installing bro on a mint box and ran into the same problem again and have another solution.

The problem with the method described here: [http://ossectools.blogspot.hk/2011/09/bro-quickstart-cluster-edition.html](http://ossectools.blogspot.hk/2011/09/bro-quickstart-cluster-edition.html) is that you are downloading the source code from the git repo.  If you use the source code from the git repo, you will get the error:
`CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
Could NOT find Libcaf (missing: LIBCAF_LIBRARIES LIBCAF_INCLUDE_DIRS)`

The solution is to download the bro source code from [https://www.bro.org/download/index.html](https://www.bro.org/download/index.html) as a .tag.gz file and then follow the instructions here: [https://www.bro.org/sphinx/install/install.html#installing-from-source](https://www.bro.org/sphinx/install/install.html#installing-from-source).

I'm not sure why the code in the git repo gives the error while the source code from the site does not.
