### ISSUE TITLE
[Python bindings] Unable to convert function return value to a Python type! when accessing caf::node_id

### ISSUE THREAD

**Issue by 1wilkens** [bro/broker#12]
When trying to access a field of type `caf::node_id` e.g. through a status update (`status.context().node`) Python exits with the error in the title.
As the error says the type from libcaf cannot be converted to a Python object, which makes sense, as `broker` does not ship with libcaf Python bindings.

Is this intended behaviour? If so then the caf types should probably not be exposed to Python at all (see: [_broker.cpp](https://github.com/bro/broker/blob/054eac298890a6de6eed8c6d9395ccf0f829054a/bindings/python/_broker.cpp#L78)).

We would really like to use the node id in our project though, is there any supported way of doing so?
For the moment we discovered that `context.__repr__` looks like it contains the node id, which lets an endpoint identify its peers (on status updates) but as `Endpoint::node_id` is not bound at all the endpoint cannot get its own id.

This is just one example of unconvertible objects. `endpoint.peers()` is unable to convert `std::vector<broker::peer_info, std::allocator<broker::peer_info>>`. Unfortunately we are not sure if this happens because of the vector itself, `broker::peer_info` or the `std::allocator`.

If we can provide any more information, please let us know :)

**Comment by jsiwek** [comment]
> When trying to access a field of type `caf::node_id` e.g. through a status update (`status.context().node`) Python exits with the error in the title.
> As the error says the type from libcaf cannot be converted to a Python object, which makes sense, as `broker` does not ship with libcaf Python bindings.
> 
> Is this intended behaviour? If so then the caf types should probably not be exposed to Python at all (see: [_broker.cpp](https://github.com/bro/broker/blob/054eac298890a6de6eed8c6d9395ccf0f829054a/bindings/python/_broker.cpp#L78)).

I just removed the `EndpointInfo.node()` method as to minimize how much the CAF dependency is exposed here.

> We would really like to use the node id in our project though, is there any supported way of doing so?
> For the moment we discovered that `context.__repr__` looks like it contains the node id, which lets an endpoint identify its peers (on status updates) but as `Endpoint::node_id` is not bound at all the endpoint cannot get its own id.

Yes, I agree being able to obtain the node ID string is helpful.  Via 
df6525e, there's now the additional `repr()` available for Endpoint that prints a node ID, and additionally I've just made explicit `node_id()` methods for both `Endpoint` and `EndpointInfo`.

> This is just one example of unconvertible objects. `endpoint.peers()` is unable to convert `std::vector<broker::peer_info, std::allocator<broker::peer_info>>`. Unfortunately we are not sure if this happens because of the vector itself, `broker::peer_info` or the `std::allocator`.

This should be fixed via 7582523.
