### ISSUE TITLE
Python Bindings: "unpeer" linked to "broker::endpoint::peer"

### ISSUE THREAD

**Issue by Monkstar** [bro/broker#13]
In line 259 in the [_broker.cpp](https://github.com/bro/broker/blob/master/bindings/python/_broker.cpp) there is this bit of code in the endpoint class: .def("unpeer", &broker::endpoint::peer)

It appears that the "unpeer" function is linked to the "peer" function in the endpoint. I assume this is not intended?

**Comment by jsiwek** [comment]
Yes, that looked wrong, thanks.
