### ISSUE TITLE
Differentiate error from status messages (Python bindings)

### ISSUE THREAD

**Issue by Monkstar** [bro/broker#15]
So I have a status subscriber here in my pybroker which receives both status and error messages. Now I just received an error. Unfortunately I was unable to reproduce the error in my more complicated, dynamic setup. But I managed to recreate it with a simple script:

```
import broker

ep = broker.Endpoint()
status = ep.make_status_subscriber(True)
ep.peer("127.0.0.1", 9999, retry=0)
# this peer does not exist so it will produce an error on our status
# subscriber

s = status.get()

if s.code() == broker.SC.PeerAdded:
    print("Hurra")
else:
    print("Nope")
```

This produces the error I received in my original setup as well:

```
Traceback (most recent call last):
  File (path removed for privacy reasons), line 11, in <module>
    if s.code() == broker.SC.PeerAdded:
TypeError: __eq__(): incompatible function arguments. The following argument types are supported:
    1. (self: broker._broker.SC, arg0: broker._broker.SC) -> bool

Invoked with: SC.PeerAdded, 4
```

The problem obviously is that the SC codes only go up to 3 while the error message (which is not part of the SC enum) has the number 4. Of course, I should first check if this really is a status message, but here is the problem: I can't. There is almost (see next paragraph) no way to check if the value I receive with `status.get()` is an error or a status. In the `_broker.cpp` for the Python Bindings I can see that there is in fact a `ValueType` class that supports checks like `isError` but it appears to be unusable in the Python files.

It discovered that is possible to use `if isinstance(s, broker._broker.Error):` in order to find out if it is an error, but I assume that the `_broker` class is supposed to be hidden and therefore not to be accessed by the users, so I think it might be a good idea to implement a check for error messages for the status_subscriber output in order to avoid dirty workarounds.

**Comment by Monkstar** [comment]
I also found this in the `__init__.py`:

```
    def _to_error_or_status(self, x):
        if x.is_error():
            return x.get_error()

        if x.is_status():
            return x.get_status()
```

So apparently the internal python func for the status subscriber actually checks INTERNALLY if the object you receive via 'get()' is a status or error and then returns the appropriate cast object, however without telling the user which one it is then. Maybe this should be exposed instead of internal so I can do the checking and typecasting myself and then perform the proper handling.

**Comment by jsiwek** [comment]
> It discovered that is possible to use `if isinstance(s, broker._broker.Error):` in order to find out if it is an error, but I assume that the `_broker` class is supposed to be hidden and therefore not to be accessed by the users, so I think it might be a good idea to implement a check for error messages for the status_subscriber output in order to avoid dirty workarounds.

`broker._broker.Error` is now available as `broker.Error`, seems like it was either oversight or done to just not conflict with an exception type name (which I've also now changed to be more appropriate anyway, see 04171eb).

So you could, if you find it less verbose, define a function like:

```python
def is_error(msg):
    return isinstance(msg, broker.Error)
```

(This also would have still been possible before using the inverse logic with `broker.Status` since there's only two types it can be)
