### ISSUE TITLE
Python Bindings: "unpeer_nosync" missing

### ISSUE THREAD

**Issue by Monkstar** [bro/broker#19]
Hi,

first of all, thanks for all the quick fixes during the past few weeks. I have another request now, as I can not find the `unpeer_nosync()` function from the `endpoint` class in the python bindings (it does, however, already exist in the C++ code). I would be very glad if you could add that as I really need non-blocking operations in my code.

Thanks!

**Comment by jsiwek** [comment]
It's added in `master` now.
