### ISSUE TITLE
CAF Dependencies

### ISSUE THREAD

**Issue by JCobeyTanium** [bro/broker#2]
In the README.rst, under dependenciese, the CAF version is as follows.

"CAF (C++ Actor Framework) version 0.14+"

Making the assumption that the "+" means "this version or later" is incorrect. The Cmake fails with the following error on the current release of CAF.

"CMake Error at CMakeLists.txt:21 (message):
Broker requires CAF version 0.14, older and newer versions are not supported."

I suggest removing the "+" from the dependency requirement.

**Comment by mavam** [comment]
Thanks for the note. We're currently in the process of rewriting Broker internally (in branch `topic/matthias/actor-system`). Once the rewrite is complete, we'll also update the dependencies. At this point, we require the development branch of CAF. With the next Broker release, there will also be a definite CAF release to point to.
