### ISSUE TITLE
"Peer added" status message sometimes triggered AFTER the first topic message

### ISSUE THREAD

**Issue by Monkstar** [bro/broker#20]
Hey,

it's me again. I'm having a little problem here with the timing of status messages. I am simulating a network here on my computer that obviously doesn't really have delays and I believe this is part of the problem, but still I think the problem should not exist.

My Python program has several endpoints that communicate. When an endpoint peers with another endpoint and gets its "Peer added" status, it sends a "HELLO" message to transmit some basic info. Now, my endpoints are programmed not to accept messages from peers they are not connected to, and they update their connection lists through these status messages. If a message arrives from someone that is not in their list, they discard it. This leads to the problem that the "HELLO" message gets lost in some rare cases, because the message subscriber is ready for reading BEFORE the status subscriber (which I check via select() and file descriptors for the subscribers). See this example here:

```
18 Oct 12:12:44 Tree 1: Message received. Topic: '/connect/78830909B4E33CE60E3E435C005F360572365E1'. Content: '{"sender_id": "DF572413EFA22C7E4F34966686B32C57132F541", "receiver_id": "78830909B4E33CE60E3E435C005F360572365E1", "sender_IP": "172.17.0.7", "descendants": 0, "number": 1, "leaves": 3, "replacement_id": null, "code": "200"}' 
18 Oct 12:12:44 Tree 1: WARNING! Received message from sender not in my connected_nodes list.  
18 Oct 12:12:44 Tree 1: Peer added. Node ID: 'DF572' IP: '::ffff:172.17.0.7'. Port: 41442. 
```

I do not know how this is handled internally in broker, but is it possible to guarantee that message subscribers will not be ready until the status subscribers say that the peer sending the message has been added? (If not, what are the internal mechanics for that so I can try handling it differently?). I can deal with simultaneousness; my program always prioritizes status subscribers if they are ready at the same time that a message subscriber is, but if the message subscriber actually is ready BEFORE the status subscriber, the program fails. And I do not really want to buffer messages from unknown peers until they are connected as it might lead to even more problems.

**Comment by jsiwek** [comment]
Could you try using the `topic/sync-peer-added` branch (fa6a251) and let me know if it fixes the issue?

Essentially there was potentially multi-threaded scheduling shenanigans going on and I've tried to add an explicit synchronization such that the "peer added" status message should be fully processed and trigger readiness for any `status_subscriber` before anything else happens (other messages that have already been received should remain queued and ineligible for other threads to process until this synchronization finishes).

**Comment by Monkstar** [comment]
Thank you! Yes, I will try that branch. However, I can not reliably reproduce the problem (as you pointed out, it is a multi-threaded scheduling problem and even with my rather large amount of tests it only occurs every other day or so with a single network participant) so I will not be able to say for sure whether it is solved or not. I can of course inform you in case it does occur again, which I will notice.

**Comment by Monkstar** [comment]
I just had this again:

```
23 Oct 16:02:21 Tree 0: Message received. Topic: '/connect/5E5FDA66335EFA9AABC4ED743E0E380663D2421'. Content: '{"sender_id": "C3C8920260ADAC77FCAABFC7EAECCF03D71BC91", "receiver_id": "5E5FDA66335EFA9AABC4ED743E0E380663D2421", "sender_IP": "172.17.0.6", "descendants": 0, "number": 0, "leaves": 2, "cost": 2, "lowest_cost": null, "replacement_id": null, "code": "200"}' 
23 Oct 16:02:21 Tree 0: WARNING! Received message from sender not in my connected_nodes list: C3C89 
23 Oct 16:02:21 Tree 0: Peer added. Node ID: 'C3C89' IP: '::ffff:172.17.0.6'. Port: 36878. 
```

I pulled my the branch in docker (with all previous images cleaned) via `RUN git clone https://github.com/bro/broker --recursive --branch topic/sync-peer-added`. This should be correct, shouldn't it? If so, the bug still exists unfortunately.

**Comment by jsiwek** [comment]
Yeah, I think you tested right.

However, at least now I've got an artificial way to simulate/reproduce this by manually sleeping the thread before this line:

https://github.com/bro/broker/blob/a843bfab047999386c6268a47bb2f6969b7bbaf7/src/status_subscriber.cc#L28

And I also still see the issue with the `topic/sync-peer-added` branch, so I'll look into it more.

**Comment by jsiwek** [comment]
The `master` branch now has a new fix in it.  Let me know if you still see this happen.

**Comment by Monkstar** [comment]
So, this is not a huge problem for me right now as my system can handle this and merely reports a warning, but this bug also occurs in the opposite direction: I just received a message from a Broker endpoint after that endpoint had already unpeered. I don't know if this is a priority for you, but I thought you might want to know.
