### ISSUE TITLE
ping.py - Vector passed instead of int

### ISSUE THREAD

**Issue by neslog** [bro/broker#23]
When testing the broker example I got the following error.

warning: failed to convert remote event 'ping' arg #0, got vector, expected int

Here's the fix that worked for me:

     23     ping = broker.bro.Event("ping", [n]);
Had to remove the brackets around "n".  Replaced with this.
     23     ping = broker.bro.Event("ping", n);

**Comment by jsiwek** [comment]
Updated, thanks for pointing that out.
